server:
  port: 8060

spring:
  datasource:
    name: hxw-security
    url: jdbc:mysql://localhost:3306/hxw_security?useSSL=false&rewriteBatchedStatements=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true

  redis:
    # 数据库索引
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数
        max-active: 100
        # 最大阻塞等待时间(负数表示无限制)
        max-wait: 2000
        # 最大空间
        max-idle: 500
        # 最小空闲
        min-idle: 8
    # 连接超时时间
    timeout: 5000

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token \u8FC7\u671F\u65F6\u95F4 2\u4E2A\u5C0F\u65F6
  expiration: 7200000
  auth:
    # \u6388\u6743\u8DEF\u5F84
    path: /login
    # \u83B7\u53D6\u7528\u6237\u4FE1\u606F
    account: /info
